# NUMPY

Numpy is general purpose Array Preprocessing package. it provides high performance multi dimension array objects and tools for working with these arrays.

## What is an array?

Array is a data structure that can store values of same data types. in Python this is the main difference between a list and an Array as list can store items with different data types but arrays can't.

In [3]:
# First import the numpy library
import numpy as np

In [4]:
lst= [1,2,3,4,5]
arr = np.array(lst)

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
arr.shape

(5,)

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr

array([1, 2, 3, 4, 5])

In [9]:
## Multi dim array
lst1 = [1,2,3,4,5]
lst2 = [6,7,8,9,10]
lst3 = [11,12,13,14,15]
arr_new = np.array([lst1,lst2,lst3])

In [10]:
print(arr_new)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [11]:
# .shape will return (rows, columns)
arr_new.shape

(3, 5)

In [12]:
# Reshape can convert the array into different shape providing the total number of items remain the same
arr_new.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [13]:
# Indexing of 1D arrays
a1 = np.array([1,2,3,4])

In [14]:
print (a1)

[1 2 3 4]


In [15]:
a1[2]

3

In [16]:
# Indexing of Multi dimension arrays
a2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [17]:
# print all the values
a2[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
# print first 2 column data only
a2[:,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [19]:
# print data from last 2 rows last 2 columns
a2[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [20]:
# arrange function
arr3 = np.arange(0,20,2)

In [21]:
print(arr3)

[ 0  2  4  6  8 10 12 14 16 18]


In [22]:
# linspace to equally divide the values in that range
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
# Copy function and broadcasting
ar = np.arange(0,10)

In [24]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# Broadasting is applying same value to all the items
ar[3:] = 100

In [26]:
print(ar)

[  0   1   2 100 100 100 100 100 100 100]


In [28]:
ar1=ar
print(ar1)

[  0   1   2 100 100 100 100 100 100 100]


In [29]:
ar1[3:0] = 200

In [30]:
# Printing same values as Arrays are pass by reference
print(ar)
print(ar1)

[  0   1   2 100 100 100 100 100 100 100]
[  0   1   2 100 100 100 100 100 100 100]


In [32]:
# in order to get the value into another variable without affeccting the original memory location use COPY'
ar = np.arange(1,10)
ar[4:]=100
print(ar)

[  1   2   3   4 100 100 100 100 100]


In [33]:
ar2=ar.copy()
ar2[4:]=200
print(ar)
print(ar2)

[  1   2   3   4 100 100 100 100 100]
[  1   2   3   4 200 200 200 200 200]


### important things in Exploratory data analysis

In [34]:
print(ar)

[  1   2   3   4 100 100 100 100 100]


In [35]:
# to check condition for each item in array
ar>5

array([False, False, False, False,  True,  True,  True,  True,  True])

In [41]:
# to get the items satisfying the conditon
ar[ar>3]

array([  4, 100, 100, 100, 100, 100])

In [37]:
# to multiply or add each item with a number
ar*5

array([  5,  10,  15,  20, 500, 500, 500, 500, 500])

In [38]:
ar+5

array([  6,   7,   8,   9, 105, 105, 105, 105, 105])

In [44]:
print(ar)
print(ar2)
print(ar*ar2)

[  1   2   3   4 100 100 100 100 100]
[  1   2   3   4 200 200 200 200 200]
[    1     4     9    16 20000 20000 20000 20000 20000]


In [45]:
# to create arrays with 1's in 1D
np.ones(4,int)

array([1, 1, 1, 1])

In [46]:
# to create arrays with 1s in Multi dim
np.ones((3,4),float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [50]:
# to generate random values in array use Random
np.random.randint(2,40,(2,5))

array([[15, 38, 27, 21, 34],
       [17, 26, 27, 10, 35]])